#!/usr/bin/env php
<?php

include __DIR__ . '/vendor/autoload.php';

$app = new \Symfony\Component\Console\Application();

$app->add(new \Timberphp\TimberChain\Commands\ExecuteCommand());

$app->run();